name: Blank Issue
description: Create a blank issue. ALWAYS FIRST USE OUR SUPPORT CHANNEL! ONLY USE THIS FORM IF YOU ARE A CONTRIBUTOR OR WERE TOLD TO DO SO IN THE SUPPORT CHANNEL.

body:
    - type: markdown
      attributes:
          value: |
              GitHub Issues are for development and tracked bugs in Nv.
              If your report is specifically about the installer flow, include whether it happened in `NvInstaller`.

    - type: textarea
      id: content
      attributes:
          label: Content
      validations:
          required: true

    - type: checkboxes
      id: agreement-check
      attributes:
          label: Request Agreement
          options:
              - label: I have read the requirements for opening an issue above
                required: true
