blank_issues_enabled: false
contact_links:
    - name: Nv Repository
      url: https://github.com/o9/nv
      about: Main repository for Nv source code, releases, and issue tracking.
    - name: Nv Installer
      url: https://github.com/o9/nvInstaller
      about: Standalone installer source and release repository for Nv.
